// Code generated by protoc-gen-go.
// source: im.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	im.proto

It has these top-level messages:
	Connect
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeType int32

const (
	NodeType_NodeTypeMin     NodeType = 0
	NodeType_NodeTypeIos     NodeType = 1
	NodeType_NodeTypeAndroid NodeType = 2
	NodeType_NodeTypeWeb     NodeType = 3
)

var NodeType_name = map[int32]string{
	0: "NodeTypeMin",
	1: "NodeTypeIos",
	2: "NodeTypeAndroid",
	3: "NodeTypeWeb",
}
var NodeType_value = map[string]int32{
	"NodeTypeMin":     0,
	"NodeTypeIos":     1,
	"NodeTypeAndroid": 2,
	"NodeTypeWeb":     3,
}

func (x NodeType) String() string {
	return proto1.EnumName(NodeType_name, int32(x))
}
func (NodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MsgType int32

const (
	MsgType_MsgTypeUnknown MsgType = 0
	MsgType_MsgTypeConnect MsgType = 1
	MsgType_MsgTypeConnack MsgType = 2
	MsgType_MsgTypeQuit    MsgType = 3
	MsgType_MsgTypePing    MsgType = 5
	MsgType_MsgTypePong    MsgType = 6
)

var MsgType_name = map[int32]string{
	0: "MsgTypeUnknown",
	1: "MsgTypeConnect",
	2: "MsgTypeConnack",
	3: "MsgTypeQuit",
	5: "MsgTypePing",
	6: "MsgTypePong",
}
var MsgType_value = map[string]int32{
	"MsgTypeUnknown": 0,
	"MsgTypeConnect": 1,
	"MsgTypeConnack": 2,
	"MsgTypeQuit":    3,
	"MsgTypePing":    5,
	"MsgTypePong":    6,
}

func (x MsgType) String() string {
	return proto1.EnumName(MsgType_name, int32(x))
}
func (MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Connect struct {
	Version  string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	NodeType int32  `protobuf:"varint,3,opt,name=nodeType" json:"nodeType,omitempty"`
}

func (m *Connect) Reset()                    { *m = Connect{} }
func (m *Connect) String() string            { return proto1.CompactTextString(m) }
func (*Connect) ProtoMessage()               {}
func (*Connect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Connect) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Connect) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Connect) GetNodeType() int32 {
	if m != nil {
		return m.NodeType
	}
	return 0
}

func init() {
	proto1.RegisterType((*Connect)(nil), "proto.Connect")
	proto1.RegisterEnum("proto.NodeType", NodeType_name, NodeType_value)
	proto1.RegisterEnum("proto.MsgType", MsgType_name, MsgType_value)
}

func init() { proto1.RegisterFile("im.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd0, 0x3f, 0x4b, 0xc5, 0x30,
	0x14, 0x05, 0x70, 0xf3, 0x4a, 0x5e, 0xeb, 0x15, 0x7c, 0x97, 0xe8, 0x10, 0x9c, 0x8a, 0x53, 0xe9,
	0xe0, 0xe2, 0x27, 0x10, 0x27, 0x87, 0x8a, 0x16, 0x8b, 0xb3, 0x6d, 0x43, 0x09, 0xc5, 0x7b, 0x4b,
	0x1b, 0xff, 0x7d, 0x7b, 0x31, 0x4d, 0x35, 0x38, 0xe5, 0x9c, 0x1f, 0xe1, 0x40, 0x02, 0x99, 0x7d,
	0xbd, 0x9a, 0x66, 0x76, 0xac, 0xa4, 0x3f, 0x2e, 0x1b, 0x48, 0x6f, 0x99, 0xc8, 0x74, 0x4e, 0x69,
	0x48, 0xdf, 0xcd, 0xbc, 0x58, 0x26, 0x2d, 0x72, 0x51, 0x1c, 0xd7, 0x5b, 0x55, 0xe7, 0x20, 0x1d,
	0x8f, 0x86, 0xf4, 0xce, 0xfb, 0x5a, 0xd4, 0x05, 0x64, 0xc4, 0xbd, 0x79, 0xfa, 0x9a, 0x8c, 0x4e,
	0x72, 0x51, 0xc8, 0xfa, 0xb7, 0x97, 0x35, 0x64, 0xf7, 0x21, 0xab, 0x03, 0x9c, 0x6c, 0xb9, 0xb2,
	0x84, 0x47, 0x31, 0xdc, 0xf1, 0x82, 0x42, 0x9d, 0xc1, 0x61, 0x83, 0x1b, 0xea, 0x67, 0xb6, 0x3d,
	0xee, 0xe2, 0x5b, 0xcf, 0xa6, 0xc5, 0xa4, 0xfc, 0x84, 0xb4, 0x5a, 0x06, 0x3f, 0xa9, 0xe0, 0x34,
	0xc4, 0x86, 0x46, 0xe2, 0x8f, 0x9f, 0xd5, 0x3f, 0x0b, 0x0f, 0x42, 0xf1, 0xcf, 0x5e, 0xba, 0x71,
	0xdd, 0x0d, 0xf6, 0xf8, 0x66, 0x1d, 0x26, 0x11, 0x3c, 0x58, 0x1a, 0x50, 0xc6, 0xc0, 0x34, 0xe0,
	0xbe, 0xdd, 0xfb, 0xbf, 0xba, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xa0, 0xbb, 0x4e, 0x3e,
	0x01, 0x00, 0x00,
}
