// Code generated by protoc-gen-go.
// source: im.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	im.proto

It has these top-level messages:
	ScHello
*/
package proto

import proto1 "extra/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type NT int32

const (
	NT_NT_Ios     NT = 0
	NT_NT_Android NT = 1
	NT_NT_Web     NT = 2
)

var NT_name = map[int32]string{
	0: "NT_Ios",
	1: "NT_Android",
	2: "NT_Web",
}
var NT_value = map[string]int32{
	"NT_Ios":     0,
	"NT_Android": 1,
	"NT_Web":     2,
}

func (x NT) String() string {
	return proto1.EnumName(NT_name, int32(x))
}
func (NT) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MT int32

const (
	MT_MT_Unknown MT = 0
	MT_MT_ScHello MT = 1
)

var MT_name = map[int32]string{
	0: "MT_Unknown",
	1: "MT_ScHello",
}
var MT_value = map[string]int32{
	"MT_Unknown": 0,
	"MT_ScHello": 1,
}

func (x MT) String() string {
	return proto1.EnumName(MT_name, int32(x))
}
func (MT) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ScHello struct {
	Rand string `protobuf:"bytes,1,opt,name=rand" json:"rand,omitempty"`
}

func (m *ScHello) Reset()                    { *m = ScHello{} }
func (m *ScHello) String() string            { return proto1.CompactTextString(m) }
func (*ScHello) ProtoMessage()               {}
func (*ScHello) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto1.RegisterType((*ScHello)(nil), "proto.ScHello")
	proto1.RegisterEnum("proto.NT", NT_name, NT_value)
	proto1.RegisterEnum("proto.MT", MT_name, MT_value)
}

func init() { proto1.RegisterFile("im.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0xcc, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xb2, 0x5c, 0xec, 0xc1, 0xc9, 0x1e, 0xa9,
	0x39, 0x39, 0xf9, 0x42, 0x42, 0x5c, 0x2c, 0x45, 0x89, 0x79, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x60, 0xb6, 0x96, 0x0e, 0x17, 0x93, 0x5f, 0x88, 0x10, 0x17, 0x17, 0x9b, 0x5f, 0x48,
	0xbc, 0x67, 0x7e, 0xb1, 0x00, 0x83, 0x10, 0x1f, 0x17, 0x97, 0x5f, 0x48, 0xbc, 0x63, 0x5e, 0x4a,
	0x51, 0x7e, 0x66, 0x8a, 0x00, 0x23, 0x54, 0x2e, 0x3c, 0x35, 0x49, 0x80, 0x49, 0x4b, 0x85, 0x8b,
	0xc9, 0x37, 0x04, 0xa4, 0xc2, 0x37, 0x24, 0x3e, 0x34, 0x2f, 0x3b, 0x2f, 0xbf, 0x3c, 0x0f, 0xa2,
	0xc3, 0x37, 0x24, 0x1e, 0x6a, 0x8b, 0x00, 0x63, 0x12, 0x1b, 0xd8, 0x66, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x4b, 0xde, 0xfb, 0x25, 0x8c, 0x00, 0x00, 0x00,
}
