// Code generated by protoc-gen-go.
// source: im.proto
// DO NOT EDIT!

/*
Package improto is a generated protocol buffer package.

It is generated from these files:
	im.proto

It has these top-level messages:
	RspMsg
*/
package improto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgType int32

const (
	MsgType_PingReq  MsgType = 257
	MsgType_PingRsq  MsgType = 258
	MsgType_LoginReq MsgType = 259
	MsgType_LoginRsp MsgType = 260
)

var MsgType_name = map[int32]string{
	257: "PingReq",
	258: "PingRsq",
	259: "LoginReq",
	260: "LoginRsp",
}
var MsgType_value = map[string]int32{
	"PingReq":  257,
	"PingRsq":  258,
	"LoginReq": 259,
	"LoginRsp": 260,
}

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}
func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (x *MsgType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgType_value, data, "MsgType")
	if err != nil {
		return err
	}
	*x = MsgType(value)
	return nil
}
func (MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RspMsg struct {
	RspCode          *int32  `protobuf:"varint,1,req,name=rsp_code" json:"rsp_code,omitempty"`
	RspMsg           *string `protobuf:"bytes,2,opt,name=rsp_msg" json:"rsp_msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RspMsg) Reset()                    { *m = RspMsg{} }
func (m *RspMsg) String() string            { return proto.CompactTextString(m) }
func (*RspMsg) ProtoMessage()               {}
func (*RspMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RspMsg) GetRspCode() int32 {
	if m != nil && m.RspCode != nil {
		return *m.RspCode
	}
	return 0
}

func (m *RspMsg) GetRspMsg() string {
	if m != nil && m.RspMsg != nil {
		return *m.RspMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*RspMsg)(nil), "improto.RspMsg")
	proto.RegisterEnum("improto.MsgType", MsgType_name, MsgType_value)
}

func init() { proto.RegisterFile("im.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0xcc, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0xcc, 0x05, 0x33, 0x94, 0xb4, 0xb9, 0xd8, 0x82, 0x8a,
	0x0b, 0x7c, 0x8b, 0xd3, 0x85, 0x04, 0xb8, 0x38, 0x8a, 0x8a, 0x0b, 0xe2, 0x93, 0xf3, 0x53, 0x52,
	0x25, 0x18, 0x15, 0x98, 0x34, 0x58, 0x85, 0xf8, 0xb9, 0xd8, 0x41, 0x22, 0xb9, 0xc5, 0xe9, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x5a, 0xce, 0x5c, 0xec, 0x40, 0x95, 0x21, 0x95, 0x05, 0xa9, 0x42,
	0x3c, 0x5c, 0xec, 0x01, 0x99, 0x79, 0xe9, 0x41, 0xa9, 0x85, 0x02, 0x8d, 0x4c, 0x70, 0x5e, 0x71,
	0xa1, 0x40, 0x13, 0x93, 0x10, 0x2f, 0x17, 0x87, 0x4f, 0x7e, 0x7a, 0x66, 0x1e, 0x48, 0xb2, 0x19,
	0x89, 0x5b, 0x5c, 0x20, 0xd0, 0xc2, 0x04, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xb3, 0x49, 0xe0,
	0x85, 0x00, 0x00, 0x00,
}
